/*
SQLyog v10.2 
MySQL - 5.7.26 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `sys_dict_data` (
	`dict_code` bigint (20),
	`dict_sort` int (4),
	`dict_label` varchar (300),
	`dict_value` varchar (300),
	`dict_type` varchar (300),
	`css_class` varchar (300),
	`list_class` varchar (300),
	`is_default` char (3),
	`status` char (3),
	`create_by` varchar (192),
	`create_time` datetime ,
	`update_by` varchar (192),
	`update_time` datetime ,
	`remark` varchar (1500)
); 
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('1','1','男','0','sys_user_sex','','','Y','0','admin','2022-11-18 09:03:45','',NULL,'性别男');
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('2','2','女','1','sys_user_sex','','','N','0','admin','2022-11-18 09:03:45','',NULL,'性别女');
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('3','3','未知','2','sys_user_sex','','','N','0','admin','2022-11-18 09:03:45','',NULL,'性别未知');
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('4','1','显示','0','sys_show_hide','','primary','Y','0','admin','2022-11-18 09:03:45','',NULL,'显示菜单');
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('5','2','隐藏','1','sys_show_hide','','danger','N','0','admin','2022-11-18 09:03:45','',NULL,'隐藏菜单');
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('6','1','正常','0','sys_normal_disable','','primary','Y','0','admin','2022-11-18 09:03:45','',NULL,'正常状态');
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('7','2','停用','1','sys_normal_disable','','danger','N','0','admin','2022-11-18 09:03:45','',NULL,'停用状态');
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('8','1','正常','0','sys_job_status','','primary','Y','0','admin','2022-11-18 09:03:45','',NULL,'正常状态');
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('9','2','暂停','1','sys_job_status','','danger','N','0','admin','2022-11-18 09:03:45','',NULL,'停用状态');
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('10','1','默认','DEFAULT','sys_job_group','','','Y','0','admin','2022-11-18 09:03:45','',NULL,'默认分组');
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('11','2','系统','SYSTEM','sys_job_group','','','N','0','admin','2022-11-18 09:03:45','',NULL,'系统分组');
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('12','1','是','Y','sys_yes_no','','primary','Y','0','admin','2022-11-18 09:03:45','',NULL,'系统默认是');
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('13','2','否','N','sys_yes_no','','danger','N','0','admin','2022-11-18 09:03:45','',NULL,'系统默认否');
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('14','1','通知','1','sys_notice_type','','warning','Y','0','admin','2022-11-18 09:03:45','',NULL,'通知');
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('15','2','公告','2','sys_notice_type','','success','N','0','admin','2022-11-18 09:03:45','',NULL,'公告');
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('16','1','正常','0','sys_notice_status','','primary','Y','0','admin','2022-11-18 09:03:45','',NULL,'正常状态');
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('17','2','关闭','1','sys_notice_status','','danger','N','0','admin','2022-11-18 09:03:45','',NULL,'关闭状态');
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('18','99','其他','0','sys_oper_type','','info','N','0','admin','2022-11-18 09:03:45','',NULL,'其他操作');
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('19','1','新增','1','sys_oper_type','','info','N','0','admin','2022-11-18 09:03:45','',NULL,'新增操作');
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('20','2','修改','2','sys_oper_type','','info','N','0','admin','2022-11-18 09:03:45','',NULL,'修改操作');
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('21','3','删除','3','sys_oper_type','','danger','N','0','admin','2022-11-18 09:03:45','',NULL,'删除操作');
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('22','4','授权','4','sys_oper_type','','primary','N','0','admin','2022-11-18 09:03:45','',NULL,'授权操作');
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('23','5','导出','5','sys_oper_type','','warning','N','0','admin','2022-11-18 09:03:45','',NULL,'导出操作');
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('24','6','导入','6','sys_oper_type','','warning','N','0','admin','2022-11-18 09:03:45','',NULL,'导入操作');
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('25','7','强退','7','sys_oper_type','','danger','N','0','admin','2022-11-18 09:03:45','',NULL,'强退操作');
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('26','8','生成代码','8','sys_oper_type','','warning','N','0','admin','2022-11-18 09:03:45','',NULL,'生成操作');
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('27','9','清空数据','9','sys_oper_type','','danger','N','0','admin','2022-11-18 09:03:45','',NULL,'清空操作');
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('28','1','成功','0','sys_common_status','','primary','N','0','admin','2022-11-18 09:03:45','',NULL,'正常状态');
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('29','2','失败','1','sys_common_status','','danger','N','0','admin','2022-11-18 09:03:45','',NULL,'停用状态');
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('30','0','在校','0','student_tag',NULL,'default','N','0','admin','2022-11-21 05:04:27','',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('31','1','请假离校','1','student_tag',NULL,'default','N','0','admin','2022-11-21 05:05:08','',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('32','2','未返校','2','student_tag',NULL,'default','N','0','admin','2022-11-21 05:05:29','',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('33','3','当日返校','3','student_tag',NULL,'default','N','0','admin','2022-11-21 05:05:38','',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('34','0','无管控','0','control_level',NULL,'default','N','0','admin','2022-11-21 05:06:47','',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('35','1','校内居家监测','1','control_level',NULL,'default','N','0','admin','2022-11-21 05:07:04','',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('36','2','校内居家隔离','2','control_level',NULL,'default','N','0','admin','2022-11-21 05:07:30','',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('37','3','校外集中隔离','3','control_level',NULL,'default','N','0','admin','2022-11-21 05:07:44','',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('38','0','因疫暂缓','0','not_school_reason',NULL,'default','N','0','admin','2022-11-21 05:08:29','',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('39','1','因就业实习暂缓','1','not_school_reason',NULL,'default','N','0','admin','2022-11-21 05:08:42','',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('40','2','因其他暂缓返','2','not_school_reason',NULL,'default','N','0','admin','2022-11-21 05:08:52','admin','2022-11-21 05:09:03',NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('41','0','低风险','0','risk_level',NULL,'default','N','0','admin','2022-11-21 05:09:54','',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('42','1','高风险','1','risk_level',NULL,'default','N','0','admin','2022-11-21 05:10:04','',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('43','0','省内','0','place_to_school',NULL,'default','N','0','admin','2022-11-21 05:10:44','',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('44','1','省外','1','place_to_school',NULL,'default','N','0','admin','2022-11-21 05:10:50','',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('45','0','报备','0','holiday_type',NULL,'default','N','0','admin','2022-11-21 05:11:29','',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('46','1','请假','1','holiday_type',NULL,'default','N','0','admin','2022-11-21 05:11:34','',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('47','0','市内','0','destination_type',NULL,'default','N','0','admin','2022-11-21 05:12:19','',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('48','1','省内市外','1','destination_type',NULL,'default','N','0','admin','2022-11-21 05:12:37','',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('49','2','省外','2','destination_type',NULL,'default','N','0','admin','2022-11-21 05:12:47','',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('50','0','硕士研究生','0','training_level',NULL,'default','N','0','admin','2022-11-22 04:39:11','',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('51','1','博士研究生','1','training_level',NULL,'default','N','0','admin','2022-11-22 04:39:19','',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('52','0','汉族','0','nation',NULL,'default','N','0','admin','2022-11-22 04:39:55','',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('53','1','回族','1','nation',NULL,'default','N','0','admin','2022-11-22 04:40:02','',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('54','0','雁塔校区','0','campus',NULL,'default','N','0','admin','2022-11-22 04:41:07','',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('55','1','长安校区','1','campus',NULL,'default','N','0','admin','2022-11-22 04:41:12','',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('56','0','宿舍区','0','accommodation',NULL,'default','N','0','admin','2022-11-22 04:42:09','',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('57','1','家属区','1','accommodation',NULL,'default','N','0','admin','2022-11-22 04:42:18','',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('58','2','走读生','2','accommodation',NULL,'default','N','0','admin','2022-11-22 04:42:30','',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('59','0','博士1号楼','0','accommodation_park',NULL,'default','N','0','admin','2022-11-22 04:43:53','',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('60','1','博士2号楼','1','accommodation_park',NULL,'default','N','0','admin','2022-11-22 04:44:09','',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('61','1','竹园1号楼','2','accommodation_park',NULL,'default','N','0','admin','2022-11-22 04:44:19','',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('62','0','教育学部','0','deptName',NULL,NULL,'N','0','',NULL,'',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('63','1','马克思主义学院','1','deptName',NULL,NULL,'N','0','',NULL,'',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('64','2','哲学学院','2','deptName',NULL,NULL,'N','0','',NULL,'',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('65','3','国家安全学院(政法与公共管理学院)','3','deptName',NULL,NULL,'N','0','',NULL,'',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('66','4','文学院','4','deptName',NULL,NULL,'N','0','',NULL,'',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('67','5','历史文化学院','5','deptName',NULL,NULL,'N','0','',NULL,'',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('68','6','心理学院','6','deptName',NULL,NULL,'N','0','',NULL,'',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('69','7','外国语学院','7','deptName',NULL,NULL,'N','0','',NULL,'',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('70','8','数学与统计学院','8','deptName',NULL,NULL,'N','0','',NULL,'',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('71','9','物理学与信息技术学院','9','deptName',NULL,NULL,'N','0','',NULL,'',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('72','10','化学化工学院','10','deptName',NULL,NULL,'N','0','',NULL,'',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('73','11','材料科学与工程学院','11','deptName',NULL,NULL,'N','0','',NULL,'',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('74','12','生命科学学院','12','deptName',NULL,NULL,'N','0','',NULL,'',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('75','13','地理科学与旅游学院','13','deptName',NULL,NULL,'N','0','',NULL,'',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('76','14','计算机科学学院','14','deptName',NULL,NULL,'N','0','',NULL,'',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('77','15','新闻与传播学院','15','deptName',NULL,NULL,'N','0','',NULL,'',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('78','16','体育学院','16','deptName',NULL,NULL,'N','0','',NULL,'',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('79','17','音乐学院','17','deptName',NULL,NULL,'N','0','',NULL,'',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('80','18','美术学院','18','deptName',NULL,NULL,'N','0','',NULL,'',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('81','19','国际商学院','19','deptName',NULL,NULL,'N','0','',NULL,'',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('82','20','国际汉学院','20','deptName',NULL,NULL,'N','0','',NULL,'',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('83','21','食品工程与营养科学学院','21','deptName',NULL,NULL,'N','0','',NULL,'',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('84','22','民族教育学院','22','deptName',NULL,NULL,'N','0','',NULL,'',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('85','23','教师干部培训学院','23','deptName',NULL,NULL,'N','0','',NULL,'',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('86','24','远程教育学院','24','deptName',NULL,NULL,'N','0','',NULL,'',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('87','25','基础实验教学中心','25','deptName',NULL,NULL,'N','0','',NULL,'',NULL,NULL);
insert into `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) values('88','26','','26','',NULL,NULL,'N','0','',NULL,'',NULL,NULL);
