package com.slabbridge.core.mapper;

import com.slabbridge.core.entity.EnterpriseInfo;
import com.slabbridge.core.entity.EnterpriseInfoExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface EnterpriseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table el_enterprise_info
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    long countByExample(EnterpriseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table el_enterprise_info
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    int deleteByExample(EnterpriseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table el_enterprise_info
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table el_enterprise_info
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    int insert(EnterpriseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table el_enterprise_info
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    int insertSelective(@Param("record") EnterpriseInfo record, @Param("selective") EnterpriseInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table el_enterprise_info
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    EnterpriseInfo selectOneByExample(EnterpriseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table el_enterprise_info
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    EnterpriseInfo selectOneByExampleWithBLOBs(EnterpriseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table el_enterprise_info
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    List<EnterpriseInfo> selectByExampleWithBLOBs(EnterpriseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table el_enterprise_info
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    List<EnterpriseInfo> selectByExample(EnterpriseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table el_enterprise_info
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    EnterpriseInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table el_enterprise_info
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    EnterpriseInfo selectByPrimaryKeyWithLogicalDelete(@Param("id") Long id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table el_enterprise_info
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    int updateByExampleSelective(@Param("record") EnterpriseInfo record, @Param("example") EnterpriseInfoExample example, @Param("selective") EnterpriseInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table el_enterprise_info
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") EnterpriseInfo record, @Param("example") EnterpriseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table el_enterprise_info
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    int updateByExample(@Param("record") EnterpriseInfo record, @Param("example") EnterpriseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table el_enterprise_info
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    int updateByPrimaryKeySelective(@Param("record") EnterpriseInfo record, @Param("selective") EnterpriseInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table el_enterprise_info
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(EnterpriseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table el_enterprise_info
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    int updateByPrimaryKey(EnterpriseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table el_enterprise_info
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    int batchInsert(@Param("list") List<EnterpriseInfo> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table el_enterprise_info
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    int batchInsertSelective(@Param("list") List<EnterpriseInfo> list, @Param("selective") EnterpriseInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table el_enterprise_info
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    int batchDelete(@Param("ids") List ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table el_enterprise_info
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    int logicalDeleteByExample(@Param("example") EnterpriseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table el_enterprise_info
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    int logicalDeleteByPrimaryKey(Long id);
}