package com.slabbridge.core.entity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

public class EnterpriseInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table el_enterprise_info
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public static final Byte IS_DELETED = IsDeleted.IS_DELETED.value();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table el_enterprise_info
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public static final Byte NOT_DELETED = IsDeleted.NOT_DELETED.value();

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_enterprise_info.id
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_enterprise_info.account
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_enterprise_info.pwd
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_enterprise_info.name
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_enterprise_info.type
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_enterprise_info.person_scale
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    private Integer personScale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_enterprise_info.registered_capital
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    private Float registeredCapital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_enterprise_info.registered_date
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    private Date registeredDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_enterprise_info.area_covered
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    private Float areaCovered;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_enterprise_info.legal_person
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    private String legalPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_enterprise_info.email
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_enterprise_info.phone_no
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    private String phoneNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_enterprise_info.street
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    private Integer street;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_enterprise_info.street_name
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    private String streetName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_enterprise_info.is_keypoint
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    private Byte isKeypoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_enterprise_info.province
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    private Integer province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_enterprise_info.city
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    private Integer city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_enterprise_info.district
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    private Integer district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_enterprise_info.address
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_enterprise_info.logo_image
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    private String logoImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_enterprise_info.created_by
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_enterprise_info.created_at
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_enterprise_info.updated_by
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_enterprise_info.updated_at
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_enterprise_info.deleted_by
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    private String deletedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_enterprise_info.is_deleted
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    private Byte isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_enterprise_info.biz_park
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    private String bizPark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_enterprise_info.qualification
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    private String qualification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_enterprise_info.business
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    private String business;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_enterprise_info.nature
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    private String nature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_enterprise_info.credit_code
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    private String creditCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_enterprise_info.market_name
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    private String marketName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column el_enterprise_info.introduce
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    private String introduce;

    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_enterprise_info.id
     *
     * @return the value of el_enterprise_info.id
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_enterprise_info.id
     *
     * @param id the value for el_enterprise_info.id
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_enterprise_info.account
     *
     * @return the value of el_enterprise_info.account
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_enterprise_info.account
     *
     * @param account the value for el_enterprise_info.account
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_enterprise_info.pwd
     *
     * @return the value of el_enterprise_info.pwd
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_enterprise_info.pwd
     *
     * @param pwd the value for el_enterprise_info.pwd
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_enterprise_info.name
     *
     * @return the value of el_enterprise_info.name
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_enterprise_info.name
     *
     * @param name the value for el_enterprise_info.name
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_enterprise_info.type
     *
     * @return the value of el_enterprise_info.type
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_enterprise_info.type
     *
     * @param type the value for el_enterprise_info.type
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_enterprise_info.person_scale
     *
     * @return the value of el_enterprise_info.person_scale
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public Integer getPersonScale() {
        return personScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_enterprise_info.person_scale
     *
     * @param personScale the value for el_enterprise_info.person_scale
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public void setPersonScale(Integer personScale) {
        this.personScale = personScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_enterprise_info.registered_capital
     *
     * @return the value of el_enterprise_info.registered_capital
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public Float getRegisteredCapital() {
        return registeredCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_enterprise_info.registered_capital
     *
     * @param registeredCapital the value for el_enterprise_info.registered_capital
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public void setRegisteredCapital(Float registeredCapital) {
        this.registeredCapital = registeredCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_enterprise_info.registered_date
     *
     * @return the value of el_enterprise_info.registered_date
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public Date getRegisteredDate() {
        return registeredDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_enterprise_info.registered_date
     *
     * @param registeredDate the value for el_enterprise_info.registered_date
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public void setRegisteredDate(Date registeredDate) {
        this.registeredDate = registeredDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_enterprise_info.area_covered
     *
     * @return the value of el_enterprise_info.area_covered
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public Float getAreaCovered() {
        return areaCovered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_enterprise_info.area_covered
     *
     * @param areaCovered the value for el_enterprise_info.area_covered
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public void setAreaCovered(Float areaCovered) {
        this.areaCovered = areaCovered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_enterprise_info.legal_person
     *
     * @return the value of el_enterprise_info.legal_person
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public String getLegalPerson() {
        return legalPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_enterprise_info.legal_person
     *
     * @param legalPerson the value for el_enterprise_info.legal_person
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public void setLegalPerson(String legalPerson) {
        this.legalPerson = legalPerson == null ? null : legalPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_enterprise_info.email
     *
     * @return the value of el_enterprise_info.email
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_enterprise_info.email
     *
     * @param email the value for el_enterprise_info.email
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_enterprise_info.phone_no
     *
     * @return the value of el_enterprise_info.phone_no
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_enterprise_info.phone_no
     *
     * @param phoneNo the value for el_enterprise_info.phone_no
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_enterprise_info.street
     *
     * @return the value of el_enterprise_info.street
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public Integer getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_enterprise_info.street
     *
     * @param street the value for el_enterprise_info.street
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public void setStreet(Integer street) {
        this.street = street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_enterprise_info.street_name
     *
     * @return the value of el_enterprise_info.street_name
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public String getStreetName() {
        return streetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_enterprise_info.street_name
     *
     * @param streetName the value for el_enterprise_info.street_name
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public void setStreetName(String streetName) {
        this.streetName = streetName == null ? null : streetName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_enterprise_info.is_keypoint
     *
     * @return the value of el_enterprise_info.is_keypoint
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public Byte getIsKeypoint() {
        return isKeypoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_enterprise_info.is_keypoint
     *
     * @param isKeypoint the value for el_enterprise_info.is_keypoint
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public void setIsKeypoint(Byte isKeypoint) {
        this.isKeypoint = isKeypoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_enterprise_info.province
     *
     * @return the value of el_enterprise_info.province
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public Integer getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_enterprise_info.province
     *
     * @param province the value for el_enterprise_info.province
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public void setProvince(Integer province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_enterprise_info.city
     *
     * @return the value of el_enterprise_info.city
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_enterprise_info.city
     *
     * @param city the value for el_enterprise_info.city
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public void setCity(Integer city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_enterprise_info.district
     *
     * @return the value of el_enterprise_info.district
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public Integer getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_enterprise_info.district
     *
     * @param district the value for el_enterprise_info.district
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public void setDistrict(Integer district) {
        this.district = district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_enterprise_info.address
     *
     * @return the value of el_enterprise_info.address
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_enterprise_info.address
     *
     * @param address the value for el_enterprise_info.address
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_enterprise_info.logo_image
     *
     * @return the value of el_enterprise_info.logo_image
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public String getLogoImage() {
        return logoImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_enterprise_info.logo_image
     *
     * @param logoImage the value for el_enterprise_info.logo_image
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public void setLogoImage(String logoImage) {
        this.logoImage = logoImage == null ? null : logoImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_enterprise_info.created_by
     *
     * @return the value of el_enterprise_info.created_by
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_enterprise_info.created_by
     *
     * @param createdBy the value for el_enterprise_info.created_by
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_enterprise_info.created_at
     *
     * @return the value of el_enterprise_info.created_at
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_enterprise_info.created_at
     *
     * @param createdAt the value for el_enterprise_info.created_at
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_enterprise_info.updated_by
     *
     * @return the value of el_enterprise_info.updated_by
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_enterprise_info.updated_by
     *
     * @param updatedBy the value for el_enterprise_info.updated_by
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_enterprise_info.updated_at
     *
     * @return the value of el_enterprise_info.updated_at
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_enterprise_info.updated_at
     *
     * @param updatedAt the value for el_enterprise_info.updated_at
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_enterprise_info.deleted_by
     *
     * @return the value of el_enterprise_info.deleted_by
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public String getDeletedBy() {
        return deletedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_enterprise_info.deleted_by
     *
     * @param deletedBy the value for el_enterprise_info.deleted_by
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public void setDeletedBy(String deletedBy) {
        this.deletedBy = deletedBy == null ? null : deletedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table el_enterprise_info
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public void andLogicalDeleted(boolean deleted) {
        setIsDeleted(deleted ? IsDeleted.IS_DELETED.value() : IsDeleted.NOT_DELETED.value());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_enterprise_info.is_deleted
     *
     * @return the value of el_enterprise_info.is_deleted
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_enterprise_info.is_deleted
     *
     * @param isDeleted the value for el_enterprise_info.is_deleted
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_enterprise_info.biz_park
     *
     * @return the value of el_enterprise_info.biz_park
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public String getBizPark() {
        return bizPark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_enterprise_info.biz_park
     *
     * @param bizPark the value for el_enterprise_info.biz_park
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public void setBizPark(String bizPark) {
        this.bizPark = bizPark == null ? null : bizPark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_enterprise_info.qualification
     *
     * @return the value of el_enterprise_info.qualification
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public String getQualification() {
        return qualification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_enterprise_info.qualification
     *
     * @param qualification the value for el_enterprise_info.qualification
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public void setQualification(String qualification) {
        this.qualification = qualification == null ? null : qualification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_enterprise_info.business
     *
     * @return the value of el_enterprise_info.business
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public String getBusiness() {
        return business;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_enterprise_info.business
     *
     * @param business the value for el_enterprise_info.business
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public void setBusiness(String business) {
        this.business = business == null ? null : business.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_enterprise_info.nature
     *
     * @return the value of el_enterprise_info.nature
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public String getNature() {
        return nature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_enterprise_info.nature
     *
     * @param nature the value for el_enterprise_info.nature
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public void setNature(String nature) {
        this.nature = nature == null ? null : nature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_enterprise_info.credit_code
     *
     * @return the value of el_enterprise_info.credit_code
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public String getCreditCode() {
        return creditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_enterprise_info.credit_code
     *
     * @param creditCode the value for el_enterprise_info.credit_code
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public void setCreditCode(String creditCode) {
        this.creditCode = creditCode == null ? null : creditCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_enterprise_info.market_name
     *
     * @return the value of el_enterprise_info.market_name
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public String getMarketName() {
        return marketName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_enterprise_info.market_name
     *
     * @param marketName the value for el_enterprise_info.market_name
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public void setMarketName(String marketName) {
        this.marketName = marketName == null ? null : marketName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column el_enterprise_info.introduce
     *
     * @return the value of el_enterprise_info.introduce
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column el_enterprise_info.introduce
     *
     * @param introduce the value for el_enterprise_info.introduce
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table el_enterprise_info
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public enum IsDeleted {
        NOT_DELETED(new Byte("0"), "Î´É¾³ý"),
        IS_DELETED(new Byte("1"), "ÒÑÉ¾³ý");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table el_enterprise_info
         *
         * @mbg.generated Mon Apr 12 11:40:32 CST 2021
         */
        private final Byte value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table el_enterprise_info
         *
         * @mbg.generated Mon Apr 12 11:40:32 CST 2021
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table el_enterprise_info
         *
         * @mbg.generated Mon Apr 12 11:40:32 CST 2021
         */
        IsDeleted(Byte value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table el_enterprise_info
         *
         * @mbg.generated Mon Apr 12 11:40:32 CST 2021
         */
        public Byte getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table el_enterprise_info
         *
         * @mbg.generated Mon Apr 12 11:40:32 CST 2021
         */
        public Byte value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table el_enterprise_info
         *
         * @mbg.generated Mon Apr 12 11:40:32 CST 2021
         */
        public String getName() {
            return this.name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table el_enterprise_info
         *
         * @mbg.generated Mon Apr 12 11:40:32 CST 2021
         */
        public static IsDeleted parseValue(Byte value) {
            if (value != null) {
                for (IsDeleted item : values()) {
                    if (item.value.equals(value)) {
                        return item;
                    }
                }
            }
            return null;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table el_enterprise_info
         *
         * @mbg.generated Mon Apr 12 11:40:32 CST 2021
         */
        public static IsDeleted parseName(String name) {
            if (name != null) {
                for (IsDeleted item : values()) {
                    if (item.name.equals(name)) {
                        return item;
                    }
                }
            }
            return null;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table el_enterprise_info
     *
     * @mbg.generated Mon Apr 12 11:40:32 CST 2021
     */
    public enum Column {
        id("id", "id", "BIGINT", false),
        account("account", "account", "VARCHAR", false),
        pwd("pwd", "pwd", "VARCHAR", false),
        name("name", "name", "VARCHAR", true),
        type("type", "type", "VARCHAR", true),
        personScale("person_scale", "personScale", "INTEGER", false),
        registeredCapital("registered_capital", "registeredCapital", "REAL", false),
        registeredDate("registered_date", "registeredDate", "DATE", false),
        areaCovered("area_covered", "areaCovered", "REAL", false),
        legalPerson("legal_person", "legalPerson", "VARCHAR", false),
        email("email", "email", "VARCHAR", false),
        phoneNo("phone_no", "phoneNo", "VARCHAR", false),
        street("street", "street", "INTEGER", false),
        streetName("street_name", "streetName", "VARCHAR", false),
        isKeypoint("is_keypoint", "isKeypoint", "TINYINT", false),
        province("province", "province", "INTEGER", false),
        city("city", "city", "INTEGER", false),
        district("district", "district", "INTEGER", false),
        address("address", "address", "VARCHAR", false),
        logoImage("logo_image", "logoImage", "VARCHAR", false),
        createdBy("created_by", "createdBy", "VARCHAR", false),
        createdAt("created_at", "createdAt", "TIMESTAMP", false),
        updatedBy("updated_by", "updatedBy", "VARCHAR", false),
        updatedAt("updated_at", "updatedAt", "TIMESTAMP", false),
        deletedBy("deleted_by", "deletedBy", "VARCHAR", false),
        isDeleted("is_deleted", "isDeleted", "TINYINT", false),
        bizPark("biz_park", "bizPark", "VARCHAR", false),
        qualification("qualification", "qualification", "VARCHAR", false),
        business("business", "business", "VARCHAR", false),
        nature("nature", "nature", "VARCHAR", false),
        creditCode("credit_code", "creditCode", "VARCHAR", false),
        marketName("market_name", "marketName", "VARCHAR", false),
        introduce("introduce", "introduce", "LONGVARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table el_enterprise_info
         *
         * @mbg.generated Mon Apr 12 11:40:32 CST 2021
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table el_enterprise_info
         *
         * @mbg.generated Mon Apr 12 11:40:32 CST 2021
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table el_enterprise_info
         *
         * @mbg.generated Mon Apr 12 11:40:32 CST 2021
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table el_enterprise_info
         *
         * @mbg.generated Mon Apr 12 11:40:32 CST 2021
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table el_enterprise_info
         *
         * @mbg.generated Mon Apr 12 11:40:32 CST 2021
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table el_enterprise_info
         *
         * @mbg.generated Mon Apr 12 11:40:32 CST 2021
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table el_enterprise_info
         *
         * @mbg.generated Mon Apr 12 11:40:32 CST 2021
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table el_enterprise_info
         *
         * @mbg.generated Mon Apr 12 11:40:32 CST 2021
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table el_enterprise_info
         *
         * @mbg.generated Mon Apr 12 11:40:32 CST 2021
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table el_enterprise_info
         *
         * @mbg.generated Mon Apr 12 11:40:32 CST 2021
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table el_enterprise_info
         *
         * @mbg.generated Mon Apr 12 11:40:32 CST 2021
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table el_enterprise_info
         *
         * @mbg.generated Mon Apr 12 11:40:32 CST 2021
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table el_enterprise_info
         *
         * @mbg.generated Mon Apr 12 11:40:32 CST 2021
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table el_enterprise_info
         *
         * @mbg.generated Mon Apr 12 11:40:32 CST 2021
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table el_enterprise_info
         *
         * @mbg.generated Mon Apr 12 11:40:32 CST 2021
         */
        public static Column[] all() {
            return Column.values();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table el_enterprise_info
         *
         * @mbg.generated Mon Apr 12 11:40:32 CST 2021
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table el_enterprise_info
         *
         * @mbg.generated Mon Apr 12 11:40:32 CST 2021
         */
        public String getAliasedEscapedColumnName() {
            StringBuilder sb = new StringBuilder();
            sb.append("enterpriseinfo.");
            sb.append(this.getEscapedColumnName());
            sb.append(" as ");
            if (this.isColumnNameDelimited) {
                sb.append(BEGINNING_DELIMITER);
            }
            sb.append("enterpriseinfo_");
            sb.append(this.column);
            if (this.isColumnNameDelimited) {
                sb.append(BEGINNING_DELIMITER);
            }
            return sb.toString();
        }
    }
}