
create type DWA_PROJECTBASEPRICE_MANU_Table as table
(
	communityId nvarchar(20) null ,
	communityName nvarchar(200) null ,
	communityAddress nvarchar(1024) null ,
	countyName nvarchar(200) null ,
	blockName nvarchar(200) null ,
	loopName nvarchar(200) null ,
	hasIndex int null ,
	isPstCalc int null ,
	status int null ,
	label nvarchar(200) null ,
	propertyType nvarchar(200) null ,
	projectType nvarchar(200) null ,
	projectTypeDtl nvarchar(200) null ,
	propertyLevel nvarchar(200) null ,
	year int null ,
	area decimal(18, 2) null ,
	areaCoefficient decimal(7, 4) null ,
	yearCoefficient decimal(7, 4) null ,
	comment nvarchar(1024) null ,
	basePriceDraft decimal(18, 2) null ,
	mainPriceDraft decimal(18, 2) null ,
	basePrice_1 decimal(18, 2) null ,
	voppat nvarchar(200) null ,
	voppa decimal(18, 2) null ,
	priceUnitAdj decimal(18, 2) null ,
	visitedNum int null ,
	firstVisitTime date null ,
	visitedNum15 int null ,
	visitedNum30 int null ,
	priceDealMean_1 decimal(18, 2) null ,
	priceDealMax_1 decimal(18, 2) null ,
	sumDeal_1 int null ,
	priceDealMean decimal(18, 2) null ,
	priceDealMax decimal(18, 2) null ,
	sumDeal int null ,
	priceListedMin decimal(18, 2) null ,
	priceCase1_ToAI_Pst decimal(18, 6) null ,
	priceCase2_ToAI_Pst decimal(18, 6) null ,
	priceCase1_ToLst_Pst decimal(18, 6) null ,
	priceCase2_ToLst_Pst decimal(18, 6) null ,
	priceCase1 decimal(18, 2) null ,
	priceCase1AdjPst decimal(18, 6) null ,
	sumCase1 int null ,
	priceCase2 decimal(18, 2) null ,
	priceCase2AdjPst decimal(18, 6) null ,
	sumCase2 int null ,
	voppbt nvarchar(200) null ,
	voppb decimal(18, 6) null ,
	bindCommunityId int null ,
	bindCommunityPst decimal(18, 6) null ,
	bindBlockClass nvarchar(200) null ,
	bindBlockClassPst decimal(18, 6) null ,
	bindBlockPropertyLevel nvarchar(200) null ,
	bindBlockPropertyLevelPst decimal(18, 6) null ,
	bindBlockProjectType nvarchar(200) null ,
	bindBlockProjectTypePst decimal(18, 6) null ,
	bindCountyProjectType nvarchar(200) null ,
	bindCountyProjectTypePst decimal(18, 6) null
)